services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
      MYSQL_ROOT_HOST: '%'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"  
    environment:
      PMA_HOST: mysql_server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mysql_server

volumes:
  db_data:
